controller_joint_names: ['', 'JOINT_1', 'JOINT_3', 'JOINT_5', 'JOINT_2', 'JOINT_4', 'JOINT_6', 'JOINT_7', 'JOINT_9', 'JOINT_11', 'JOINT_13', 'JOINT_15', 'JOINT_8', 'JOINT_10', 'JOINT_12', 'JOINT_14', 'JOINT_16', ]
